config/routes.rb
Rails.application.routes.draw do
  resources :register_products
  root 'pages#home'

  get 'pages/home', as: 'home'
  get 'pages/catalog', as: 'catalog'
  get 'pages/products', as: 'products'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/register_product.rb
class RegisterProduct < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def catalog
  end

  def products
    ## Trás todos os registros da tabela Products
    @products = Product.all
    render :json => @products
  end
  
end

app/controllers/register_products_controller.rb
class RegisterProductsController < ApplicationController
  before_action :set_register_product, only: [:show, :edit, :update, :destroy]

  # GET /register_products
  # GET /register_products.json
  def index
    @register_products = RegisterProduct.all
  end

  # GET /register_products/1
  # GET /register_products/1.json
  def show
  end

  # GET /register_products/new
  def new
    @register_product = RegisterProduct.new
  end

  # GET /register_products/1/edit
  def edit
  end

  # POST /register_products
  # POST /register_products.json
  def create
    @register_product = RegisterProduct.new(register_product_params)

    respond_to do |format|
      if @register_product.save
        format.html { redirect_to @register_product, notice: 'Register product was successfully created.' }
        format.json { render :show, status: :created, location: @register_product }
      else
        format.html { render :new }
        format.json { render json: @register_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /register_products/1
  # PATCH/PUT /register_products/1.json
  def update
    respond_to do |format|
      if @register_product.update(register_product_params)
        format.html { redirect_to @register_product, notice: 'Register product was successfully updated.' }
        format.json { render :show, status: :ok, location: @register_product }
      else
        format.html { render :edit }
        format.json { render json: @register_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /register_products/1
  # DELETE /register_products/1.json
  def destroy
    @register_product.destroy
    respond_to do |format|
      format.html { redirect_to register_products_url, notice: 'Register product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register_product
      @register_product = RegisterProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def register_product_params
      params.require(:register_product).permit(:nome, :id_seq, :endereco, :preco, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/register_products_helper.rb
module RegisterProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>CursoRails</title>
		<%= csrf_meta_tags %>
		
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="icon" href="favicon.ico">
		<link href="https://fonts.googleapis.com/css?family=Dosis:400,700|Roboto:300,400,700,900" rel="stylesheet">
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>
		<header id="main-header">
			<nav class="handy-links">
				<div class="content">
					<a class="status-pedido">STATUS DO PEDIDO</a>
					<a class="cadastro-newsletter">CADASTRO DA NEWSLETTER</a>
					<a class="identifique-se">IDENTIFIQUE-SE</a>
				</div>
			</nav>
			<div class="content">
				<div class="header-container">
					<div class="logo-wrapper">
						<%= link_to '/' do %>
							<%= image_tag 'logo.svg' %>
						<% end %>
					</div>

					<div class="header-menu">
						<nav class="site-menu">
							<a href="#">HOMEM</a>
							<a href="#">MULHER</a>
							<a href="#">KIDS</a>
							<a href="#" class="sport">ESPORTES</a>
							<a href="#">MARCAS</a>
							<a href="#" class="personalization">PERSONALIZAÇÃO</a>
						</nav>

						<div class="site-services">
							<form class="site-search">
								<input type="search" placeholder="procurar" name="q" />
							</form>
							<a id="shopping-bag">0</a>
						</div>
					</div>
				</div>
			</div>
		</header>

		<main>
			<%= yield %>
		</main>

		<footer>
			<div class="newsletter">
				<div class="content">
					<p>CADASTRE-SE, FIQUE POR DENTRO DAS NOVIDADES E GANHE <span>15% de desconto</span></p>
					<form>
						<input type="email" placeholder="SEU E-MAIL" />
						<input type="submit" value="CADASTRAR" />
					</form>
				</div>
      </div>
      
			<div class="main-footer">
				<div class="content">
					<div class="foreign-links">
						<ul>
							<li><p>PÁGINAS ESPECIAIS</p></li>
							<li>&nbsp;</li>
							<li><a href="/novidades" title="Novidades" manual_cm_sp="footer-_-páginas especiais-_-novidades">Novidades</a></li>
							<li><a href="/outlet" title="Outlet" manual_cm_sp="footer-_-páginas especiais-_-outlet">Outlet</a></li>
							<li><a href="/sneakersdasemana" manual_cm_sp="footer-_-páginas especiais-_-sneakers da semana">Sneakers da Semana&nbsp;</a></li>
							<li><a href="/black-friday" title="Black Friday" manual_cm_sp="footer-_-páginas especiais-_-black friday">Black Friday</a></li>
							<li><a href="/cyber-monday" title="Cyber Monday" manual_cm_sp="footer-_-páginas especiais-_-cyber monday">Cyber Monday</a></li>
							<li>&nbsp;</li>
							
							<li><a href="/calcados" manual_cm_sp="footer-_-páginas especiais-_-tênis">Tênis</a></li>
							<li><a href="/roupas" manual_cm_sp="footer-_-páginas especiais-_-roupas">Roupas</a></li>
							<li><a href="/acessorios" manual_cm_sp="footer-_-páginas especiais-_-acessorios">Acessorios</a></li>
							<li><a href="/blusao_quebra_vento" manual_cm_sp="footer-_-páginas especiais-_-corta vento">Corta vento</a></li>
							<li>&nbsp;</li>
							
							<li><a href="/adidasrunners" title="adidas Runners" manual_cm_sp="footer-_-páginas especiais-_-adidas runners">adidas Runners</a></li>
							<li><a href="https://www.adidas.com.br/como-lavar-tenis-de-corrida.html" title="Lavar Tenis de Corrida" manual_cm_sp="footer-_-páginas especiais-_-lavar tenis de corrida">Lavar Tenis de Corrida</a></li>
						</ul>
						
						<ul>
							<li><p>COLEÇÃO</p></li>
							<li>&nbsp;</li>
							<li><a href="/copa_do_mundo" title="Copa do Mundo FIFA 2018" manual_cm_sp="footer-_-coleção-_-copa do mundo fifa 2018">Copa do Mundo FIFA 2018</a></li>
							<li><a href="/copa-do-mundo-sitemap.html" title="Todas as Seleções" manual_cm_sp="footer-_-coleção-_-todas as seleções">Todas as Seleções</a></li>
							<li><a href="/coritiba" title="Coritiba" manual_cm_sp="footer-_-coleção-_-coritiba">Coritiba</a></li>
							<li><a href="/flamengo" title="Flamengo" manual_cm_sp="footer-_-coleção-_-flamengo">Flamengo</a></li>
							<li><a href="/palmeiras" title="Palmeiras" manual_cm_sp="footer-_-coleção-_-palmeiras">Palmeiras</a></li>
							<li><a href="/ponte_preta" title="Ponte Preta" manual_cm_sp="footer-_-coleção-_-ponte preta">Ponte Preta</a></li>
							<li><a href="/sport_recife" title="Sport Recife" manual_cm_sp="footer-_-coleção-_-sport recife">Sport Recife</a></li>
							<li><a href="/predator" manual_cm_sp="footer-_-coleção-_-predator">Predator</a></li>
							<li><a href="/real_madrid" manual_cm_sp="footer-_-coleção-_-real madrid">Real Madrid</a></li>
							<li><a href="/juventus" manual_cm_sp="footer-_-coleção-_-juventus">Juventus</a></li>
							<li>&nbsp;</li>

							<li><a href="https://ssf.adidas.com/cep/dc.action?campaignId=3021&amp;country=BR&amp;lid=PT" target="_blank" manual_cm_sp="footer-_-coleção-_-yeezy">Yeezy</a></li>
							<li><a href="/originals-tubular" manual_cm_sp="footer-_-coleção-_-tubular">Tubular</a></li>
							<li><a href="/farm?grid=true" manual_cm_sp="footer-_-coleção-_-farm">Farm</a></li>
							<li><a href="/boost" manual_cm_sp="footer-_-coleção-_-boost">Boost</a></li>
						</ul>
						
						<ul>
							<li><p>PRIVACIDADE &amp; TERMOS</p></li>
							<li>&nbsp;</li>
							<li><a href="https://www.adidas.com.br/help-topics-privacy_policy.html" title="Politica de privacidade" manual_cm_sp="footer-_-privacidade &amp; termos-_-politica de privacidade">Politica de privacidade</a></li>
							<li><a href="https://www.adidas.com.br/help-topics-terms_and_conditions.html" title="Termos e condições" manual_cm_sp="footer-_-privacidade &amp; termos-_-termos e condições">Termos e condições</a></li>
							<li><a href="/YESadidas.html" manual_cm_sp="footer-_-privacidade &amp; termos-_-termos e condições #yesadidas">Termos e Condições #YESadidas</a></li>
							<li><a href="/regulamento-influenciadores.html" manual_cm_sp="footer-_-privacidade &amp; termos-_-termos influenciadores">Termos Influenciadores</a></li>
						</ul>
						
						<ul>
							<li><p>INFORMAÇÕES CORPORATIVAS</p></li>
							<li>&nbsp;</li>
							<li><a href="http://www.adidas-group.com/en/group/profile/" rel="nofollow" title="Sobre nós" manual_cm_sp="footer-_-informações corporativaslojas-_-sobre nós">Sobre nós</a></li>
							<li><a href="http://careers.adidas-group.com/?brand=adidas" rel="nofollow" title="Carreiras" manual_cm_sp="footer-_-informações corporativaslojas-_-carreiras">Carreiras</a></li>
							<li><a href="http://www.adidas-group.com/en/media/media-contact/" rel="nofollow" title="Imprensa" manual_cm_sp="footer-_-informações corporativaslojas-_-imprensa">Imprensa</a></li>
							<li><a href="http://www.suafranquia.com/franquias/vestuario/roupas-e-acessorios/franquia-adidas/" rel="nofollow" title="Seja um franqueado" manual_cm_sp="footer-_-informações corporativaslojas-_-seja um franqueado">Seja um franqueado</a></li>
							<li><a href="/Projetos-Sociais.html" rel="nofollow" title="Ginga Social" manual_cm_sp="footer-_-informações corporativaslojas-_-ginga social">Ginga Social</a></li>
							<li>&nbsp;</li>

							<li><p>LOJAS</p></li>
							<li>&nbsp;</li>
							<li><a href="/storefinder/" title="Localizador de loja" manual_cm_sp="footer-_-informações corporativaslojas-_-localizador de lojas">Localizador de lojas</a></li>
						</ul>
						
						<ul>
							<li><p>SUPORTE AO CLIENTE</p></li>
							<li>&nbsp;</li>
							<li><a href="/customer-service-landing.html" title="Atendimento ao cliente" manual_cm_sp="footer-_-suporte ao cliente-_-atendimento ao cliente">Atendimento ao cliente</a></li>
							<li><a href="/tabela-de-tamanhos.html" manual_cm_sp="footer-_-suporte ao cliente-_-tabela de tamanhos">Tabela de Tamanhos</a></li>
							<li><a href="https://www.adidas.com.br/help-topics-FAQ.html" title="Dúvidas frequentes" manual_cm_sp="footer-_-suporte ao cliente-_-dúvidas frequentes">Dúvidas frequentes</a></li>
							<li><a href="https://www.adidas.com.br/on/demandware.store/Sites-adidas-BR-Site/pt_BR/CustomerService-ContactUs" manual_cm_sp="footer-_-suporte ao cliente-_-contate-nos">Contate-nos</a></li>
							<li><a href="https://www.adidas.com.br/help-topics-returning.html" title="Troca e devolução" manual_cm_sp="footer-_-suporte ao cliente-_-troca e devolução">Troca e devolução</a></li>
							<li><a href="https://www.adidas.com.br/help-topics-shipping.html" title="Entrega" manual_cm_sp="footer-_-suporte ao cliente-_-entregas e frete">Entregas e Frete</a></li>
							<li><a href="https://www.adidas.com.br/help-topics-payment.html" title="Opções de Pagamento" manual_cm_sp="footer-_-suporte ao cliente-_-opções de pagamento">Opções de Pagamento</a></li>
							<li><a href="https://www.adidas.com.br/help-topics-adidas_products.html" title="Produtos adidas" manual_cm_sp="footer-_-suporte ao cliente-_-produtos adidas">Produtos adidas</a></li>
							<li><a href="https://www.adidas.com.br/help-topics-sitemap.html" title="Mapa do Site" manual_cm_sp="footer-_-suporte ao cliente-_-mapa do site">Mapa do Site</a></li>
						</ul>
					</div>

					<div class="payment-methods">
						<span>Formas de pagamento:</span>
						<%= image_tag 'payment.png' %>
					</div>
				</div>
			</div>
			<div class="footer-copyright">
				<div class="content">
					ADIDAS DO BRASIL LTDS., inscrita no Cadastro Nacional de Pessoas Jurídicas ("CNPJ/MF") sob o nº 42.274.696/0025.61, no endereço Rua<br/ >
					Pataxós nº 241, Galpão 1, Bairro Jardim Magali, Município de Embú - SP, CEP 06833-073.
				</div>
			</div>
		</footer>

		<div class="cart-lightbox">
			<span class="close-button"></span>
			<div class="empty-cart">SEU CARRINHO ESTÁ VAZIO</div>

			<div class="cart-content">
				<h3>Sua sacola</h3>

				<div class="shop-products"><table></table></div>

				<div class="cart-footer">
					<a class="keep-shopping">CONTINUAR COMPRANDO</a>
					<div id="cart-total"></div>
					<a class="purchase">FINALIZAR PEDIDO</a>
				</div>
			</div>
		</div>
		<div class="overlay"/>

		<div class="loader"/>
	</body>

	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/pages/catalog.html.erb
<div class="content">
    <div class="location">
        <div class="breadcrumb">
            <a href="#">Página Inicial</a> /
            <a href="#">Homem</a> /
            <span>Roupas e calçados</span>
        </div>
        <h1>Roupas e calçados masculinos <span id="product-count"></span></h1>
    </div>

    <div id="product-grid"/>
</div>

app/views/pages/home.html.erb
<div class="banner_home">
    <%= link_to catalog_path do %>
        <%= image_tag 'banner.jpg' %>

        <div class="banner-content">
            <div class="content">
                <h2>P.O.D.SYSTEM</h2>
                <p>A união de três tecnologias inovadoras em novas cores.</p>

                <span>COMPRAR</span>
            </div>
        </div>
    <% end %>
</div>

app/views/pages/products.html.erb
<h1>Pages#products</h1>
<p>Find me in app/views/pages/products.html.erb</p>

app/views/register_products/_form.html.erb
<%= form_for(register_product) do |f| %>
  <% if register_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(register_product.errors.count, "error") %> prohibited this register_product from being saved:</h2>

      <ul>
      <% register_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :id_seq %>
    <%= f.text_field :id_seq %>
  </div>

  <div class="field">
    <%= f.label :endereco %>
    <%= f.text_area :endereco %>
  </div>

  <div class="field">
    <%= f.label :preco %>
    <%= f.text_field :preco %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/register_products/edit.html.erb
<h1>Editing Register Product</h1>

<%= render 'form', register_product: @register_product %>

<%= link_to 'Show', @register_product %> |
<%= link_to 'Back', register_products_path %>

app/views/register_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Register Products</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Id seq</th>
      <th>Endereco</th>
      <th>Preco</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @register_products.each do |register_product| %>
      <tr>
        <td><%= register_product.nome %></td>
        <td><%= register_product.id_seq %></td>
        <td><%= register_product.endereco %></td>
        <td><%= register_product.preco %></td>
        <td><%= register_product.email %></td>
        <td><%= link_to 'Show', register_product %></td>
        <td><%= link_to 'Edit', edit_register_product_path(register_product) %></td>
        <td><%= link_to 'Destroy', register_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Register Product', new_register_product_path %>

app/views/register_products/new.html.erb
<h1>New Register Product</h1>

<%= render 'form', register_product: @register_product %>

<%= link_to 'Back', register_products_path %>

app/views/register_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @register_product.nome %>
</p>

<p>
  <strong>Id seq:</strong>
  <%= @register_product.id_seq %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @register_product.endereco %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @register_product.preco %>
</p>

<p>
  <strong>Email:</strong>
  <%= @register_product.email %>
</p>

<%= link_to 'Edit', edit_register_product_path(@register_product) %> |
<%= link_to 'Back', register_products_path %>